Homework 2
================
William Donovan

``` r
library(tidyverse)
library(readxl)
library(dplyr)
library(knitr)
```

# Problem 1

`pols-month.csv` data-frame

``` r
pols_df = read_csv("data/pols-month.csv", na = c("NA", "", " ", ".")) |>
  janitor::clean_names() |>
  separate(
    mon, 
    c("year", "month", "day"), 
    sep = "-") |>
  mutate(
    month = month(
      as.numeric(month),
      label = TRUE,
      abbr = FALSE),
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem")) |>
  select(-c(prez_gop, prez_dem, day))

head(pols_df, 5)
```

    ## # A tibble: 5 × 9
    ##   year  month    gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##   <chr> <ord>      <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ## 1 1947  January       23      51     253      23      45     198 dem      
    ## 2 1947  February      23      51     253      23      45     198 dem      
    ## 3 1947  March         23      51     253      23      45     198 dem      
    ## 4 1947  April         23      51     253      23      45     198 dem      
    ## 5 1947  May           23      51     253      23      45     198 dem

`snp.csv` data-frame

``` r
snp_df = read_csv("data/snp.csv", na = c("NA", "", " ", ".")) |>
  janitor::clean_names() |>
  filter(!is.na(date)) |>
  mutate(
  date = parse_date_time2(
    date, 
    orders = "mdy", 
    cutoff_2000 = 49)) |>
  separate(
    date,
    c("year", "month", "day"),
    sep = "-") |>
  mutate(
    month = month(
      as.numeric(month),
      label = TRUE,
      abbr = FALSE)) |>
  select(-day)

head(snp_df, 5)
```

    ## # A tibble: 5 × 3
    ##   year  month close
    ##   <chr> <ord> <dbl>
    ## 1 2015  July  2080.
    ## 2 2015  June  2063.
    ## 3 2015  May   2107.
    ## 4 2015  April 2086.
    ## 5 2015  March 2068.

`unemployment.csv` data-frame

``` r
unemployment_df = read_csv("data/unemployment.csv", na = c("NA", "", " ", ".")) |>
  janitor::clean_names() |>
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment") |>
  mutate(
    month = month(
      ym(paste(year, month)),
      label = TRUE,
      abbr = FALSE),
    year = as.character(year)) |>
  filter(!is.na(unemployment))

head(unemployment_df, 5)
```

    ## # A tibble: 5 × 3
    ##   year  month    unemployment
    ##   <chr> <ord>           <dbl>
    ## 1 1948  January           3.4
    ## 2 1948  February          3.8
    ## 3 1948  March             4  
    ## 4 1948  April             3.9
    ## 5 1948  May               3.5

Joining data-sets using `left_join()`

``` r
problem1_df = left_join(pols_df, snp_df, by = c("year", "month")) |>
  left_join(unemployment_df, by = c("year", "month"))

head(problem1_df, 5)
```

    ## # A tibble: 5 × 11
    ##   year  month    gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##   <chr> <ord>      <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ## 1 1947  January       23      51     253      23      45     198 dem          NA
    ## 2 1947  February      23      51     253      23      45     198 dem          NA
    ## 3 1947  March         23      51     253      23      45     198 dem          NA
    ## 4 1947  April         23      51     253      23      45     198 dem          NA
    ## 5 1947  May           23      51     253      23      45     198 dem          NA
    ## # ℹ 1 more variable: unemployment <dbl>

These data-sets are comprised of historical political, economic, and
financial data. `pols-month.csv` contains monthly records from 1947-2015
on the numbers of governors, senators, and representatives in either the
democratic or republican party, as well as the party of the president at
the time. `snp.csv` contains the historical closing prices of the S&P
500 at the beginning of each month from 1950-2015. `unemployment.csv`
gives unemployment percentages from 1948-2015. After joining these
data-sets, the resulting data-frame, `problem1_df`, contains 822 rows
and 11 columns, covering data from January 1947 to June 2015. Key
variables include `president` (president’s party), `close`(S&P 500
closing price), and `unemployment` (monthly unemployment rates).

# Problem 2

Mr. Trash Wheel

``` r
mr_tw_df = read_excel("data/202509 Trash Wheel Collection Data.xlsx",
                      sheet = "Mr. Trash Wheel",
                      na = c("NA", "", " ", "."),
                      range = "A2:N709") |>
  janitor::clean_names() |>
  mutate(
    year = as.numeric(year),
    sports_balls = as.integer(round(sports_balls)),
    wheel = "mr_trash_wheel")
```

Professor Trash Wheel

``` r
professor_tw_df = read_excel("data/202509 Trash Wheel Collection Data.xlsx",
                             sheet = "Professor Trash Wheel",
                             na = c("NA", "", " ", "."),
                             range = "A2:M134") |>
  janitor::clean_names() |>
  mutate(
    wheel = "professor_trash_wheel")
```

Gwynns Falls Trash Wheel

``` r
gwynnda_tw_df = read_excel("data/202509 Trash Wheel Collection Data.xlsx",
                           sheet = "Gwynns Falls Trash Wheel",
                           na = c("NA", "", " ", "."),
                           range = "A2:L351") |>
  janitor::clean_names() |>
  mutate(
    wheel = "gwynns_falls_trash_wheel")
```

Joining data-sets using `bind_rows()`

``` r
problem2_df = bind_rows(mr_tw_df, professor_tw_df, gwynnda_tw_df) |>
  select(wheel, everything())

head(problem2_df)
```

    ## # A tibble: 6 × 15
    ##   wheel  dumpster month  year date                weight_tons volume_cubic_yards
    ##   <chr>     <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ## 1 mr_tr…        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ## 2 mr_tr…        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ## 3 mr_tr…        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ## 4 mr_tr…        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ## 5 mr_tr…        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ## 6 mr_tr…        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

The Trash Wheels remove litter and debris from the Inner Harbor in
Baltimore, Maryland and deposits it into dumpsters. These dumpsters are
transferred to waste-to-energy plants where the trash is incinerated and
converted to energy for homes. The data-sets contain information about
the dumpsters and their contents. There are three different Trash Wheels
included in this data-set (Mr, Professor, and Gwynns Falls Trash
Wheels), each with their own set of dumpsters and dumpster content
information. Information for the Trash Wheels includes dumpster number,
date of collection, weight and volume of litter, a breakdown of litter
type and amount, and homes powered. The total number of observations, or
number of rows, is 1188. The total weight of trash collected by
Professor Trash Wheel was 282.26 tons. The total number of cigarette
butts collected by Gwynns Falls Trash Wheel in June 2022 was 18120.

# Problem 3

`Zip Codes.csv`

``` r
zipcodes_df = read_csv("data/Zip Codes.csv", na = "NA") |>
  janitor::clean_names() |>
  select(-c(state_fips, county_code, file_date))

head(zipcodes_df, 5)
```

    ## # A tibble: 5 × 4
    ##   county county_fips zip_code neighborhood              
    ##   <chr>        <dbl>    <dbl> <chr>                     
    ## 1 Bronx        36005    10451 High Bridge and Morrisania
    ## 2 Bronx        36005    10452 High Bridge and Morrisania
    ## 3 Bronx        36005    10453 Central Bronx             
    ## 4 Bronx        36005    10454 Hunts Point and Mott Haven
    ## 5 Bronx        36005    10455 Hunts Point and Mott Haven

`Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv`

``` r
zillow_df = read_csv("data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv", na = "NA") |>
  janitor::clean_names() |>
  pivot_longer(
    cols = x2015_01_31:x2024_08_31,
    names_to = "date",
    values_to = "zillow_observed_rent_index") |>
  select(-c(region_type, state_name, metro)) |>
  rename(zip_code = region_name,
         county = county_name) |>
  mutate(
    date = ymd(str_remove(date, "x")),
    county = str_remove(county, " County"))

head(zillow_df, 5)
```

    ## # A tibble: 5 × 8
    ##   region_id size_rank zip_code state city     county date      
    ##       <dbl>     <dbl>    <dbl> <chr> <chr>    <chr>  <date>    
    ## 1     62080         4    11368 NY    New York Queens 2015-01-31
    ## 2     62080         4    11368 NY    New York Queens 2015-02-28
    ## 3     62080         4    11368 NY    New York Queens 2015-03-31
    ## 4     62080         4    11368 NY    New York Queens 2015-04-30
    ## 5     62080         4    11368 NY    New York Queens 2015-05-31
    ## # ℹ 1 more variable: zillow_observed_rent_index <dbl>

Joining using `full_join()`

``` r
problem3_df = full_join(zillow_df, zipcodes_df, by = c("county", "zip_code")) |>
  select(
    c(date,
      city,
      state,
      zip_code,
      county,
      county_fips,
      neighborhood,
      region_id,
      size_rank,
      zillow_observed_rent_index))

head(problem3_df, 5)
```

    ## # A tibble: 5 × 10
    ##   date       city     state zip_code county county_fips neighborhood region_id
    ##   <date>     <chr>    <chr>    <dbl> <chr>        <dbl> <chr>            <dbl>
    ## 1 2015-01-31 New York NY       11368 Queens       36081 West Queens      62080
    ## 2 2015-02-28 New York NY       11368 Queens       36081 West Queens      62080
    ## 3 2015-03-31 New York NY       11368 Queens       36081 West Queens      62080
    ## 4 2015-04-30 New York NY       11368 Queens       36081 West Queens      62080
    ## 5 2015-05-31 New York NY       11368 Queens       36081 West Queens      62080
    ## # ℹ 2 more variables: size_rank <dbl>, zillow_observed_rent_index <dbl>

The resulting data-set `problem3_df` contains data for New York city zip
codes and their corresponding Zillow Observed Rent Index (ZORI), when
available, between January 2015 and August 2024. The tidy data-set
contains ZORI record date, city, state, Zip Code, county, county FIPS
code, neighborhood, the Zillow unique region identifier, the Zillow
unique size ranking (based on United States Zip Code population), and
the ZORI for that Zip Code. The data-set can be used to track
fluctuations in rental prices across New York City.

Rows/observations in the data-set total to 17458. However, some Zip
Codes have missing Zillow data. Observations including ZORI data total
to 10450. There are 320 unique Zip Codes included and 43 unique
neighborhoods.

There are 173 Zip Codes included in Zip Code data but not the Zillow
data. These include:

``` r
problem3_df |>
  filter(is.na(date),
         zip_code != "11693") |>
  pull(zip_code) |>
  sort()
```

    ##   [1] 10008 10020 10041 10043 10045 10047 10048 10055 10072 10080 10081 10082
    ##  [13] 10087 10101 10102 10103 10104 10105 10106 10107 10108 10109 10110 10111
    ##  [25] 10112 10113 10114 10115 10116 10117 10118 10119 10120 10121 10122 10123
    ##  [37] 10124 10125 10126 10129 10130 10131 10132 10133 10138 10149 10150 10151
    ##  [49] 10152 10153 10154 10155 10156 10157 10158 10159 10160 10161 10163 10164
    ##  [61] 10165 10166 10167 10168 10169 10170 10171 10172 10173 10174 10175 10176
    ##  [73] 10177 10178 10179 10185 10197 10199 10213 10242 10249 10256 10259 10260
    ##  [85] 10261 10265 10268 10269 10270 10271 10272 10273 10274 10275 10276 10277
    ##  [97] 10278 10279 10281 10285 10286 10292 10302 10307 10309 10310 10311 10313
    ## [109] 10463 10464 10474 10475 10499 10550 10704 10705 10803 11001 11004 11005
    ## [121] 11040 11096 11201 11202 11224 11239 11241 11242 11243 11245 11247 11251
    ## [133] 11252 11256 11351 11352 11359 11362 11363 11371 11380 11381 11386 11405
    ## [145] 11411 11412 11413 11414 11416 11417 11419 11420 11421 11422 11423 11424
    ## [157] 11425 11427 11428 11429 11430 11431 11433 11436 11439 11451 11499 11559
    ## [169] 11580 11690 11694 11695 11697

There is one Zip Code (11693) that shows up in both data-sets, but the
entry in the Zip Code data-set has it mistakenly listed under Kings
County (Brooklyn), whereas the Zillow data-set has it listed under
Queens County (Queens), which is correct.

The additional Zip Codes not accounted for in the Zillow data-set could
be due to a number of reasons. For example, if there’s not enough
listings in a particular Zip Code, there might not be enough information
to give an accurate estimate of the ZORI for that time period. With the
sample size is too small, the variance can be high and the data may be
skewed. Another reason is the area a Zip Code encompasses could be very
small and not contain any rental information. Zip Code 10270, for
example, seems to only exist for a third of one block in the financial
district. Another Zip Code, 10117, maps to the intersection of 8th Ave
and 31st Street in Manhattan.

Rental prices during Covid fluctuated heavily. Below are the top 10 Zip
Code ZORI decreases from January 2020 to 2021.

``` r
problem3_df |>
  filter(date == "2020-01-31" | date == "2020-12-31") |>
  pivot_wider(names_from = date, 
              values_from = zillow_observed_rent_index) |>
  mutate(
    zori_difference = `2020-12-31` - `2020-01-31`) |>
  arrange(zori_difference) |>
  select(c(zip_code, county, neighborhood, zori_difference)) |>
  slice_head(n = 10) |>
  kable(
    caption = "Top 10 NYC Zip Codes by ZORI Difference (January 2020 to 2021)")
```

| zip_code | county   | neighborhood                  | zori_difference |
|---------:|:---------|:------------------------------|----------------:|
|    10001 | New York | Chelsea and Clinton           |       -730.5241 |
|    10007 | New York | Lower Manhattan               |       -718.7023 |
|    10002 | New York | Lower East Side               |       -700.9682 |
|    10069 | New York | NA                            |       -700.8353 |
|    10016 | New York | Gramercy Park and Murray Hill |       -688.9808 |
|    10009 | New York | Lower East Side               |       -685.6710 |
|    10011 | New York | Chelsea and Clinton           |       -675.7072 |
|    10003 | New York | Lower East Side               |       -672.4891 |
|    10004 | New York | Lower Manhattan               |       -668.8458 |
|    10010 | New York | Gramercy Park and Murray Hill |       -666.9254 |

Top 10 NYC Zip Codes by ZORI Difference (January 2020 to 2021)

All of the largest decreases in rental prices occurred in Manhattan.
Many of these areas are denser, wealthier, and/or have a lot of
transplants who could easily leave the city, leading to a large decrease
in demand in the rental market.
